### PR TITLE
Python 3.10

### PR DESCRIPTION
**Pull request by howetuft**
Follow Arch Python current version

### CODE REVIEW

**Comment by howetuft** [comment]
CAVEAT: you'll also have to update `boost-python2` https://aur.archlinux.org/packages/boost-python2) and `boost-python2-libs` (https://aur.archlinux.org/packages/boost-python2-libs) packages to 1.78 in order to have Appleseed compile.

**Comment by bartoszek** [comment]
Ups, accidentally pushed prev version to your master branch 😢 
Consider it merged.

**Comment by howetuft** [comment]
Thank you!
A request concerning `boost-python2` (as Appleseed relies on it): would you please be so kind port it to your github repos? This way, I could directly propose you PRs in the future!

**Comment by bartoszek** [comment]
Done: https://github.com/bartoszek/AUR-boost-python2
btw. If you would like to contribute directly, I could just add you as AUR co-maintainer ( [this is you, right](https://repology.org/maintainer/howetuft%40aur) )

**Comment by howetuft** [comment]
Thanks!

> I could just add you as AUR co-maintainer

Thank you, but I think your idea to create mirror repos in Github is more efficient (brilliant), as everybody can propose updates!

**Pull request closed without merging**
